"""add monnify accounts

Revision ID: 12e1ebee3811
Revises: f296683229ae
Create Date: 2026-08-18 14:04:53.898318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12e1ebee3811'
down_revision: Union[str, Sequence[str], None] = 'f296683229ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monnify_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('account_reference', sa.String(length=100), nullable=False),
    sa.Column('account_name', sa.String(length=200), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=150), nullable=True),
    sa.Column('bank_code', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monnify_accounts_account_number'), 'monnify_accounts', ['account_number'], unique=False)
    op.create_index(op.f('ix_monnify_accounts_account_reference'), 'monnify_accounts', ['account_reference'], unique=True)
    op.create_index(op.f('ix_monnify_accounts_user_id'), 'monnify_accounts', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monnify_accounts_user_id'), table_name='monnify_accounts')
    op.drop_index(op.f('ix_monnify_accounts_account_reference'), table_name='monnify_accounts')
    op.drop_index(op.f('ix_monnify_accounts_account_number'), table_name='monnify_accounts')
    op.drop_table('monnify_accounts')
    # ### end Alembic commands ###
