"""add wallet ledger fields

Revision ID: 186cdb6bc387
Revises: 3eddceee207c
Create Date: 2026-08-18 18:45:51.265328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '186cdb6bc387'
down_revision: Union[str, Sequence[str], None] = '3eddceee207c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('direction', sa.String(length=20), nullable=False))
    op.add_column('transactions', sa.Column('balance_before', sa.Numeric(precision=20, scale=2), nullable=False))
    op.add_column('transactions', sa.Column('balance_after', sa.Numeric(precision=20, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'balance_after')
    op.drop_column('transactions', 'balance_before')
    op.drop_column('transactions', 'direction')
    # ### end Alembic commands ###
