"""add transaction pin hash

Revision ID: 2a5b61385c7c
Revises: be040969a102
Create Date: 2026-09-22 14:16:03.118444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a5b61385c7c'
down_revision: Union[str, Sequence[str], None] = 'be040969a102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('transaction_pin_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'transaction_pin_hash')
    # ### end Alembic commands ###
