"""require monnify wallet fields

Revision ID: 3eddceee207c
Revises: 55d800bc5a52
Create Date: 2026-08-18 14:39:08.570061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eddceee207c'
down_revision: Union[str, Sequence[str], None] = '55d800bc5a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monnify_accounts', 'wallet_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('monnify_accounts', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monnify_accounts', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('monnify_accounts', 'wallet_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
