"""add crypto exchanges

Revision ID: 57de66f01201
Revises: 186cdb6bc387
Create Date: 2026-09-05 12:14:26.460032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57de66f01201'
down_revision: Union[str, Sequence[str], None] = '186cdb6bc387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_exchanges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('from_currency', sa.String(length=50), nullable=False),
    sa.Column('to_currency', sa.String(length=50), nullable=False),
    sa.Column('from_network', sa.String(length=100), nullable=True),
    sa.Column('to_network', sa.String(length=100), nullable=True),
    sa.Column('from_amount', sa.Numeric(precision=30, scale=18), nullable=False),
    sa.Column('to_amount', sa.Numeric(precision=30, scale=18), nullable=True),
    sa.Column('destination_address', sa.Text(), nullable=False),
    sa.Column('refund_address', sa.Text(), nullable=True),
    sa.Column('deposit_address', sa.Text(), nullable=True),
    sa.Column('deposit_extra_id', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rate_id', sa.String(length=255), nullable=True),
    sa.Column('provider_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crypto_exchanges_provider_transaction_id'), 'crypto_exchanges', ['provider_transaction_id'], unique=True)
    op.create_index(op.f('ix_crypto_exchanges_status'), 'crypto_exchanges', ['status'], unique=False)
    op.create_index(op.f('ix_crypto_exchanges_user_id'), 'crypto_exchanges', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crypto_exchanges_user_id'), table_name='crypto_exchanges')
    op.drop_index(op.f('ix_crypto_exchanges_status'), table_name='crypto_exchanges')
    op.drop_index(op.f('ix_crypto_exchanges_provider_transaction_id'), table_name='crypto_exchanges')
    op.drop_table('crypto_exchanges')
    # ### end Alembic commands ###
